// Generated from the IANA tz database (zone1970.tab + iso3166.tab).
// One entry per country/zone pair, so every country is findable — including the
// ones that merely share a zone with a neighbour (Oman shares Asia/Dubai, say).
// Regenerate with: scripts/gen-timezones.py

export interface TzEntry {
  tz: string;        // IANA identifier, e.g. "Asia/Kolkata"
  label: string;     // city name, or the country when it only shares another's zone
  country: string;
  cc: string;        // ISO 3166-1 alpha-2
  aliases: string[]; // extra searchable city names not present in the zone id
}

/** Packed as "tz|label|country|cc|alias,alias" to keep the bundle small. */
const PACKED: string[] = [
  'Asia/Kabul|Kabul|Afghanistan|AF|',
  'Europe/Tirane|Tirane|Albania|AL|',
  'Africa/Algiers|Algiers|Algeria|DZ|',
  'Europe/Andorra|Andorra|Andorra|AD|',
  'Africa/Lagos|Luanda|Angola|AO|',
  'America/Puerto_Rico|Anguilla|Anguilla|AI|',
  'Antarctica/Casey|Casey|Antarctica|AQ|',
  'Antarctica/Davis|Davis|Antarctica|AQ|',
  'Antarctica/DumontDUrville|DumontDUrville|Antarctica|AQ|',
  'Antarctica/Mawson|Mawson|Antarctica|AQ|',
  'Antarctica/McMurdo|McMurdo|Antarctica|AQ|',
  'Antarctica/Palmer|Palmer|Antarctica|AQ|',
  'Antarctica/Rothera|Rothera|Antarctica|AQ|',
  'Antarctica/Syowa|Syowa|Antarctica|AQ|',
  'Antarctica/Troll|Troll|Antarctica|AQ|',
  'Antarctica/Vostok|Vostok|Antarctica|AQ|',
  'America/Puerto_Rico|Antigua|Antigua & Barbuda|AG|',
  'America/Argentina/Buenos_Aires|Buenos Aires|Argentina|AR|',
  'America/Argentina/Catamarca|Catamarca|Argentina|AR|',
  'America/Argentina/Cordoba|Cordoba|Argentina|AR|',
  'America/Argentina/Jujuy|Jujuy|Argentina|AR|',
  'America/Argentina/La_Rioja|La Rioja|Argentina|AR|',
  'America/Argentina/Mendoza|Mendoza|Argentina|AR|',
  'America/Argentina/Rio_Gallegos|Rio Gallegos|Argentina|AR|',
  'America/Argentina/Salta|Salta|Argentina|AR|',
  'America/Argentina/San_Juan|San Juan|Argentina|AR|',
  'America/Argentina/San_Luis|San Luis|Argentina|AR|',
  'America/Argentina/Tucuman|Tucuman|Argentina|AR|',
  'America/Argentina/Ushuaia|Ushuaia|Argentina|AR|',
  'Asia/Yerevan|Yerevan|Armenia|AM|',
  'America/Puerto_Rico|Aruba|Aruba|AW|',
  'Australia/Adelaide|Adelaide|Australia|AU|',
  'Australia/Brisbane|Brisbane|Australia|AU|',
  'Australia/Broken_Hill|Broken Hill|Australia|AU|',
  'Australia/Darwin|Darwin|Australia|AU|',
  'Australia/Eucla|Eucla|Australia|AU|',
  'Australia/Hobart|Hobart|Australia|AU|',
  'Australia/Lindeman|Lindeman|Australia|AU|',
  'Australia/Lord_Howe|Lord Howe|Australia|AU|',
  'Antarctica/Macquarie|Macquarie|Australia|AU|',
  'Australia/Melbourne|Melbourne|Australia|AU|',
  'Australia/Perth|Perth|Australia|AU|',
  'Australia/Sydney|Sydney|Australia|AU|Melbourne,Canberra,Newcastle',
  'Europe/Vienna|Vienna|Austria|AT|',
  'Asia/Baku|Baku|Azerbaijan|AZ|',
  'America/Toronto|Nassau|Bahamas|BS|',
  'Asia/Qatar|Bahrain|Bahrain|BH|',
  'Asia/Dhaka|Dhaka|Bangladesh|BD|',
  'America/Barbados|Barbados|Barbados|BB|',
  'Europe/Minsk|Minsk|Belarus|BY|',
  'Europe/Brussels|Brussels|Belgium|BE|',
  'America/Belize|Belize|Belize|BZ|',
  'Africa/Lagos|Porto-Novo|Benin|BJ|',
  'Atlantic/Bermuda|Bermuda|Bermuda|BM|',
  'Asia/Thimphu|Thimphu|Bhutan|BT|',
  'America/La_Paz|La Paz|Bolivia|BO|',
  'Europe/Belgrade|Sarajevo|Bosnia & Herzegovina|BA|',
  'Africa/Maputo|Gaborone|Botswana|BW|',
  'America/Araguaina|Araguaina|Brazil|BR|',
  'America/Bahia|Bahia|Brazil|BR|',
  'America/Belem|Belem|Brazil|BR|',
  'America/Boa_Vista|Boa Vista|Brazil|BR|',
  'America/Campo_Grande|Campo Grande|Brazil|BR|',
  'America/Cuiaba|Cuiaba|Brazil|BR|',
  'America/Eirunepe|Eirunepe|Brazil|BR|',
  'America/Fortaleza|Fortaleza|Brazil|BR|',
  'America/Maceio|Maceio|Brazil|BR|',
  'America/Manaus|Manaus|Brazil|BR|',
  'America/Noronha|Noronha|Brazil|BR|',
  'America/Porto_Velho|Porto Velho|Brazil|BR|',
  'America/Recife|Recife|Brazil|BR|',
  'America/Rio_Branco|Rio Branco|Brazil|BR|',
  'America/Santarem|Santarem|Brazil|BR|',
  'America/Sao_Paulo|Sao Paulo|Brazil|BR|Rio de Janeiro,Brasilia,Belo Horizonte',
  'Europe/London|London|Britain (UK)|GB|Manchester,Birmingham,Edinburgh,Glasgow,Leeds,Cambridge,Oxford',
  'Indian/Chagos|Chagos|British Indian Ocean Territory|IO|',
  'Asia/Kuching|Brunei|Brunei|BN|',
  'Europe/Sofia|Sofia|Bulgaria|BG|',
  'Africa/Abidjan|Ouagadougou|Burkina Faso|BF|',
  'Africa/Maputo|Bujumbura|Burundi|BI|',
  'Asia/Bangkok|Phnom Penh|Cambodia|KH|',
  'Africa/Lagos|Douala|Cameroon|CM|',
  'America/Atikokan|Atikokan|Canada|CA|',
  'America/Blanc-Sablon|Blanc-Sablon|Canada|CA|',
  'America/Cambridge_Bay|Cambridge Bay|Canada|CA|',
  'America/Creston|Creston|Canada|CA|',
  'America/Dawson|Dawson|Canada|CA|',
  'America/Dawson_Creek|Dawson Creek|Canada|CA|',
  'America/Edmonton|Edmonton|Canada|CA|',
  'America/Fort_Nelson|Fort Nelson|Canada|CA|',
  'America/Glace_Bay|Glace Bay|Canada|CA|',
  'America/Goose_Bay|Goose Bay|Canada|CA|',
  'America/Halifax|Halifax|Canada|CA|',
  'America/Inuvik|Inuvik|Canada|CA|',
  'America/Iqaluit|Iqaluit|Canada|CA|',
  'America/Moncton|Moncton|Canada|CA|',
  'America/Rankin_Inlet|Rankin Inlet|Canada|CA|',
  'America/Regina|Regina|Canada|CA|',
  'America/Resolute|Resolute|Canada|CA|',
  'America/St_Johns|St Johns|Canada|CA|',
  'America/Swift_Current|Swift Current|Canada|CA|',
  'America/Toronto|Toronto|Canada|CA|Montreal,Ottawa,Quebec',
  'America/Vancouver|Vancouver|Canada|CA|',
  'America/Whitehorse|Whitehorse|Canada|CA|',
  'America/Winnipeg|Winnipeg|Canada|CA|',
  'Atlantic/Cape_Verde|Cape Verde|Cape Verde|CV|',
  'America/Puerto_Rico|Kralendijk|Caribbean NL|BQ|',
  'America/Panama|Cayman|Cayman Islands|KY|',
  'Africa/Lagos|Bangui|Central African Rep.|CF|',
  'Africa/Ndjamena|Ndjamena|Chad|TD|',
  'America/Coyhaique|Coyhaique|Chile|CL|',
  'Pacific/Easter|Easter|Chile|CL|',
  'America/Punta_Arenas|Punta Arenas|Chile|CL|',
  'America/Santiago|Santiago|Chile|CL|',
  'Asia/Shanghai|Shanghai|China|CN|Beijing,Shenzhen,Guangzhou,Hangzhou,Chengdu',
  'Asia/Urumqi|Urumqi|China|CN|',
  'Asia/Bangkok|Christmas|Christmas Island|CX|',
  'Asia/Yangon|Cocos|Cocos (Keeling) Islands|CC|',
  'America/Bogota|Bogota|Colombia|CO|',
  'Africa/Nairobi|Comoro|Comoros|KM|',
  'Africa/Kinshasa|Kinshasa|Congo (Dem. Rep.)|CD|',
  'Africa/Lubumbashi|Lubumbashi|Congo (Dem. Rep.)|CD|',
  'Africa/Lagos|Brazzaville|Congo (Rep.)|CG|',
  'Pacific/Rarotonga|Rarotonga|Cook Islands|CK|',
  'America/Costa_Rica|Costa Rica|Costa Rica|CR|',
  'Europe/Belgrade|Zagreb|Croatia|HR|',
  'America/Havana|Havana|Cuba|CU|',
  'America/Puerto_Rico|Curacao|Curaçao|CW|',
  'Asia/Famagusta|Famagusta|Cyprus|CY|',
  'Asia/Nicosia|Nicosia|Cyprus|CY|',
  'Europe/Prague|Prague|Czech Republic|CZ|',
  'Africa/Abidjan|Abidjan|Côte d’Ivoire|CI|',
  'Europe/Berlin|Copenhagen|Denmark|DK|',
  'Africa/Nairobi|Djibouti|Djibouti|DJ|',
  'America/Puerto_Rico|Dominica|Dominica|DM|',
  'America/Santo_Domingo|Santo Domingo|Dominican Republic|DO|',
  'Asia/Dili|Dili|East Timor|TL|',
  'Pacific/Galapagos|Galapagos|Ecuador|EC|',
  'America/Guayaquil|Guayaquil|Ecuador|EC|',
  'Africa/Cairo|Cairo|Egypt|EG|Alexandria,Giza',
  'America/El_Salvador|El Salvador|El Salvador|SV|',
  'Africa/Lagos|Malabo|Equatorial Guinea|GQ|',
  'Africa/Nairobi|Asmara|Eritrea|ER|',
  'Europe/Tallinn|Tallinn|Estonia|EE|',
  'Africa/Johannesburg|Mbabane|Eswatini (Swaziland)|SZ|',
  'Africa/Nairobi|Addis Ababa|Ethiopia|ET|',
  'Atlantic/Stanley|Stanley|Falkland Islands|FK|',
  'Atlantic/Faroe|Faroe|Faroe Islands|FO|',
  'Pacific/Fiji|Fiji|Fiji|FJ|',
  'Europe/Helsinki|Helsinki|Finland|FI|',
  'Europe/Paris|Paris|France|FR|Lyon,Marseille,Toulouse,Nice',
  'America/Cayenne|Cayenne|French Guiana|GF|',
  'Pacific/Gambier|Gambier|French Polynesia|PF|',
  'Pacific/Marquesas|Marquesas|French Polynesia|PF|',
  'Pacific/Tahiti|Tahiti|French Polynesia|PF|',
  'Asia/Dubai|Kerguelen|French S. Terr.|TF|',
  'Indian/Maldives|Kerguelen|French S. Terr.|TF|',
  'Africa/Lagos|Libreville|Gabon|GA|',
  'Africa/Abidjan|Banjul|Gambia|GM|',
  'Asia/Tbilisi|Tbilisi|Georgia|GE|',
  'Europe/Berlin|Berlin|Germany|DE|Munich,Frankfurt,Hamburg,Cologne,Stuttgart',
  'Europe/Busingen|Busingen|Germany|DE|',
  'Africa/Abidjan|Accra|Ghana|GH|',
  'Europe/Gibraltar|Gibraltar|Gibraltar|GI|',
  'Europe/Athens|Athens|Greece|GR|',
  'America/Danmarkshavn|Danmarkshavn|Greenland|GL|',
  'America/Nuuk|Nuuk|Greenland|GL|',
  'America/Scoresbysund|Scoresbysund|Greenland|GL|',
  'America/Thule|Thule|Greenland|GL|',
  'America/Puerto_Rico|Grenada|Grenada|GD|',
  'America/Puerto_Rico|Guadeloupe|Guadeloupe|GP|',
  'Pacific/Guam|Guam|Guam|GU|',
  'America/Guatemala|Guatemala|Guatemala|GT|',
  'Europe/London|Guernsey|Guernsey|GG|',
  'Africa/Abidjan|Conakry|Guinea|GN|',
  'Africa/Bissau|Bissau|Guinea-Bissau|GW|',
  'America/Guyana|Guyana|Guyana|GY|',
  'America/Port-au-Prince|Port-au-Prince|Haiti|HT|',
  'America/Tegucigalpa|Tegucigalpa|Honduras|HN|',
  'Asia/Hong_Kong|Hong Kong|Hong Kong|HK|',
  'Europe/Budapest|Budapest|Hungary|HU|',
  'Africa/Abidjan|Reykjavik|Iceland|IS|',
  'Asia/Kolkata|Kolkata|India|IN|Mumbai,Bangalore,Bengaluru,Delhi,New Delhi,Hyderabad,Chennai,Pune,Kochi,Ahmedabad,Jaipur,Noida,Gurgaon',
  'Asia/Jakarta|Jakarta|Indonesia|ID|Bandung,Surabaya',
  'Asia/Jayapura|Jayapura|Indonesia|ID|',
  'Asia/Makassar|Makassar|Indonesia|ID|',
  'Asia/Pontianak|Pontianak|Indonesia|ID|',
  'Asia/Tehran|Tehran|Iran|IR|',
  'Asia/Baghdad|Baghdad|Iraq|IQ|',
  'Europe/Dublin|Dublin|Ireland|IE|',
  'Europe/London|Isle of Man|Isle of Man|IM|',
  'Asia/Jerusalem|Jerusalem|Israel|IL|',
  'Europe/Rome|Rome|Italy|IT|Milan,Naples,Turin,Florence,Venice',
  'America/Jamaica|Jamaica|Jamaica|JM|',
  'Asia/Tokyo|Tokyo|Japan|JP|Osaka,Kyoto,Yokohama,Nagoya',
  'Europe/London|Jersey|Jersey|JE|',
  'Asia/Amman|Amman|Jordan|JO|',
  'Asia/Almaty|Almaty|Kazakhstan|KZ|',
  'Asia/Aqtau|Aqtau|Kazakhstan|KZ|',
  'Asia/Aqtobe|Aqtobe|Kazakhstan|KZ|',
  'Asia/Atyrau|Atyrau|Kazakhstan|KZ|',
  'Asia/Oral|Oral|Kazakhstan|KZ|',
  'Asia/Qostanay|Qostanay|Kazakhstan|KZ|',
  'Asia/Qyzylorda|Qyzylorda|Kazakhstan|KZ|',
  'Africa/Nairobi|Nairobi|Kenya|KE|',
  'Pacific/Kanton|Kanton|Kiribati|KI|',
  'Pacific/Kiritimati|Kiritimati|Kiribati|KI|',
  'Pacific/Tarawa|Tarawa|Kiribati|KI|',
  'Asia/Pyongyang|Pyongyang|Korea (North)|KP|',
  'Asia/Seoul|Seoul|Korea (South)|KR|Busan,Incheon',
  'Asia/Riyadh|Kuwait|Kuwait|KW|',
  'Asia/Bishkek|Bishkek|Kyrgyzstan|KG|',
  'Asia/Bangkok|Vientiane|Laos|LA|',
  'Europe/Riga|Riga|Latvia|LV|',
  'Asia/Beirut|Beirut|Lebanon|LB|',
  'Africa/Johannesburg|Maseru|Lesotho|LS|',
  'Africa/Monrovia|Monrovia|Liberia|LR|',
  'Africa/Tripoli|Tripoli|Libya|LY|',
  'Europe/Zurich|Vaduz|Liechtenstein|LI|',
  'Europe/Vilnius|Vilnius|Lithuania|LT|',
  'Europe/Brussels|Luxembourg|Luxembourg|LU|',
  'Asia/Macau|Macau|Macau|MO|',
  'Africa/Nairobi|Antananarivo|Madagascar|MG|',
  'Africa/Maputo|Blantyre|Malawi|MW|',
  'Asia/Kuala_Lumpur|Kuala Lumpur|Malaysia|MY|',
  'Asia/Kuching|Kuching|Malaysia|MY|',
  'Indian/Maldives|Maldives|Maldives|MV|',
  'Africa/Abidjan|Bamako|Mali|ML|',
  'Europe/Malta|Malta|Malta|MT|',
  'Pacific/Kwajalein|Kwajalein|Marshall Islands|MH|',
  'Pacific/Majuro|Majuro|Marshall Islands|MH|',
  'America/Martinique|Martinique|Martinique|MQ|',
  'Africa/Abidjan|Nouakchott|Mauritania|MR|',
  'Indian/Mauritius|Mauritius|Mauritius|MU|',
  'Africa/Nairobi|Mayotte|Mayotte|YT|',
  'America/Bahia_Banderas|Bahia Banderas|Mexico|MX|',
  'America/Cancun|Cancun|Mexico|MX|',
  'America/Chihuahua|Chihuahua|Mexico|MX|',
  'America/Ciudad_Juarez|Ciudad Juarez|Mexico|MX|',
  'America/Hermosillo|Hermosillo|Mexico|MX|',
  'America/Matamoros|Matamoros|Mexico|MX|',
  'America/Mazatlan|Mazatlan|Mexico|MX|',
  'America/Merida|Merida|Mexico|MX|',
  'America/Mexico_City|Mexico City|Mexico|MX|Guadalajara,Monterrey,Cancun',
  'America/Monterrey|Monterrey|Mexico|MX|',
  'America/Ojinaga|Ojinaga|Mexico|MX|',
  'America/Tijuana|Tijuana|Mexico|MX|',
  'Pacific/Chuuk|Chuuk|Micronesia|FM|',
  'Pacific/Kosrae|Kosrae|Micronesia|FM|',
  'Pacific/Pohnpei|Pohnpei|Micronesia|FM|',
  'Europe/Chisinau|Chisinau|Moldova|MD|',
  'Europe/Paris|Monaco|Monaco|MC|',
  'Asia/Hovd|Hovd|Mongolia|MN|',
  'Asia/Ulaanbaatar|Ulaanbaatar|Mongolia|MN|',
  'Europe/Belgrade|Podgorica|Montenegro|ME|',
  'America/Puerto_Rico|Montserrat|Montserrat|MS|',
  'Africa/Casablanca|Casablanca|Morocco|MA|',
  'Africa/Maputo|Maputo|Mozambique|MZ|',
  'Asia/Yangon|Yangon|Myanmar (Burma)|MM|',
  'Africa/Windhoek|Windhoek|Namibia|NA|',
  'Pacific/Nauru|Nauru|Nauru|NR|',
  'Asia/Kathmandu|Kathmandu|Nepal|NP|',
  'Europe/Brussels|Amsterdam|Netherlands|NL|',
  'Pacific/Noumea|Noumea|New Caledonia|NC|',
  'Pacific/Auckland|Auckland|New Zealand|NZ|Wellington,Christchurch',
  'Pacific/Chatham|Chatham|New Zealand|NZ|',
  'America/Managua|Managua|Nicaragua|NI|',
  'Africa/Lagos|Niamey|Niger|NE|',
  'Africa/Lagos|Lagos|Nigeria|NG|Abuja,Ibadan,Kano',
  'Pacific/Niue|Niue|Niue|NU|',
  'Pacific/Norfolk|Norfolk|Norfolk Island|NF|',
  'Europe/Belgrade|Skopje|North Macedonia|MK|',
  'Pacific/Guam|Saipan|Northern Mariana Islands|MP|',
  'Europe/Berlin|Oslo|Norway|NO|',
  'Asia/Dubai|Muscat|Oman|OM|',
  'Asia/Karachi|Karachi|Pakistan|PK|Lahore,Islamabad',
  'Pacific/Palau|Palau|Palau|PW|',
  'Asia/Gaza|Gaza|Palestine|PS|',
  'Asia/Hebron|Hebron|Palestine|PS|',
  'America/Panama|Panama|Panama|PA|',
  'Pacific/Bougainville|Bougainville|Papua New Guinea|PG|',
  'Pacific/Port_Moresby|Port Moresby|Papua New Guinea|PG|',
  'America/Asuncion|Asuncion|Paraguay|PY|',
  'America/Lima|Lima|Peru|PE|',
  'Asia/Manila|Manila|Philippines|PH|Cebu,Quezon City,Davao',
  'Pacific/Pitcairn|Pitcairn|Pitcairn|PN|',
  'Europe/Warsaw|Warsaw|Poland|PL|Krakow,Wroclaw,Gdansk',
  'Atlantic/Azores|Azores|Portugal|PT|',
  'Europe/Lisbon|Lisbon|Portugal|PT|',
  'Atlantic/Madeira|Madeira|Portugal|PT|',
  'America/Puerto_Rico|Puerto Rico|Puerto Rico|PR|',
  'Asia/Qatar|Qatar|Qatar|QA|',
  'Europe/Bucharest|Bucharest|Romania|RO|',
  'Asia/Anadyr|Anadyr|Russia|RU|',
  'Europe/Astrakhan|Astrakhan|Russia|RU|',
  'Asia/Barnaul|Barnaul|Russia|RU|',
  'Asia/Chita|Chita|Russia|RU|',
  'Asia/Irkutsk|Irkutsk|Russia|RU|',
  'Europe/Kaliningrad|Kaliningrad|Russia|RU|',
  'Asia/Kamchatka|Kamchatka|Russia|RU|',
  'Asia/Khandyga|Khandyga|Russia|RU|',
  'Europe/Kirov|Kirov|Russia|RU|',
  'Asia/Krasnoyarsk|Krasnoyarsk|Russia|RU|',
  'Asia/Magadan|Magadan|Russia|RU|',
  'Europe/Moscow|Moscow|Russia|RU|Saint Petersburg,St Petersburg',
  'Asia/Novokuznetsk|Novokuznetsk|Russia|RU|',
  'Asia/Novosibirsk|Novosibirsk|Russia|RU|',
  'Asia/Omsk|Omsk|Russia|RU|',
  'Asia/Sakhalin|Sakhalin|Russia|RU|',
  'Europe/Samara|Samara|Russia|RU|',
  'Europe/Saratov|Saratov|Russia|RU|',
  'Europe/Simferopol|Simferopol|Russia|RU|',
  'Asia/Srednekolymsk|Srednekolymsk|Russia|RU|',
  'Asia/Tomsk|Tomsk|Russia|RU|',
  'Europe/Ulyanovsk|Ulyanovsk|Russia|RU|',
  'Asia/Ust-Nera|Ust-Nera|Russia|RU|',
  'Asia/Vladivostok|Vladivostok|Russia|RU|',
  'Europe/Volgograd|Volgograd|Russia|RU|',
  'Asia/Yakutsk|Yakutsk|Russia|RU|',
  'Asia/Yekaterinburg|Yekaterinburg|Russia|RU|',
  'Africa/Maputo|Kigali|Rwanda|RW|',
  'Asia/Dubai|Reunion|Réunion|RE|',
  'Pacific/Pago_Pago|Pago Pago|Samoa (American)|AS|',
  'Pacific/Apia|Apia|Samoa (western)|WS|',
  'Europe/Rome|San Marino|San Marino|SM|',
  'Africa/Sao_Tome|Sao Tome|Sao Tome & Principe|ST|',
  'Asia/Riyadh|Riyadh|Saudi Arabia|SA|Jeddah,Mecca,Medina',
  'Africa/Abidjan|Dakar|Senegal|SN|',
  'Europe/Belgrade|Belgrade|Serbia|RS|',
  'Asia/Dubai|Mahe|Seychelles|SC|',
  'Africa/Abidjan|Freetown|Sierra Leone|SL|',
  'Asia/Singapore|Singapore|Singapore|SG|',
  'Europe/Prague|Bratislava|Slovakia|SK|',
  'Europe/Belgrade|Ljubljana|Slovenia|SI|',
  'Pacific/Guadalcanal|Guadalcanal|Solomon Islands|SB|',
  'Africa/Nairobi|Mogadishu|Somalia|SO|',
  'Africa/Johannesburg|Johannesburg|South Africa|ZA|Cape Town,Durban,Pretoria',
  'Atlantic/South_Georgia|South Georgia|South Georgia & the South Sandwich Islands|GS|',
  'Africa/Juba|Juba|South Sudan|SS|',
  'Atlantic/Canary|Canary|Spain|ES|',
  'Africa/Ceuta|Ceuta|Spain|ES|',
  'Europe/Madrid|Madrid|Spain|ES|Barcelona,Valencia,Seville',
  'Asia/Colombo|Colombo|Sri Lanka|LK|',
  'America/Puerto_Rico|St Barthelemy|St Barthelemy|BL|',
  'Africa/Abidjan|St Helena|St Helena|SH|',
  'America/Puerto_Rico|St Kitts|St Kitts & Nevis|KN|',
  'America/Puerto_Rico|St Lucia|St Lucia|LC|',
  'America/Puerto_Rico|Lower Princes|St Maarten (Dutch)|SX|',
  'America/Puerto_Rico|Marigot|St Martin (French)|MF|',
  'America/Miquelon|Miquelon|St Pierre & Miquelon|PM|',
  'America/Puerto_Rico|St Vincent|St Vincent|VC|',
  'Africa/Khartoum|Khartoum|Sudan|SD|',
  'America/Paramaribo|Paramaribo|Suriname|SR|',
  'Europe/Berlin|Longyearbyen|Svalbard & Jan Mayen|SJ|',
  'Europe/Berlin|Stockholm|Sweden|SE|',
  'Europe/Zurich|Zurich|Switzerland|CH|',
  'Asia/Damascus|Damascus|Syria|SY|',
  'Asia/Taipei|Taipei|Taiwan|TW|',
  'Asia/Dushanbe|Dushanbe|Tajikistan|TJ|',
  'Africa/Nairobi|Dar es Salaam|Tanzania|TZ|',
  'Asia/Bangkok|Bangkok|Thailand|TH|Phuket,Chiang Mai',
  'Africa/Abidjan|Lome|Togo|TG|',
  'Pacific/Fakaofo|Fakaofo|Tokelau|TK|',
  'Pacific/Tongatapu|Tongatapu|Tonga|TO|',
  'America/Puerto_Rico|Port of Spain|Trinidad & Tobago|TT|',
  'Africa/Tunis|Tunis|Tunisia|TN|',
  'Europe/Istanbul|Istanbul|Turkey|TR|Ankara,Izmir',
  'Asia/Ashgabat|Ashgabat|Turkmenistan|TM|',
  'America/Grand_Turk|Grand Turk|Turks & Caicos Is|TC|',
  'Pacific/Tarawa|Funafuti|Tuvalu|TV|',
  'Pacific/Midway|Midway|US minor outlying islands|UM|',
  'Pacific/Wake|Wake|US minor outlying islands|UM|',
  'Africa/Nairobi|Kampala|Uganda|UG|',
  'Europe/Kyiv|Kyiv|Ukraine|UA|Kiev,Lviv,Odesa',
  'Europe/Simferopol|Simferopol|Ukraine|UA|',
  'Asia/Dubai|Dubai|United Arab Emirates|AE|Abu Dhabi,Sharjah',
  'America/Adak|Adak|United States|US|',
  'America/Anchorage|Anchorage|United States|US|',
  'America/North_Dakota/Beulah|Beulah|United States|US|',
  'America/Boise|Boise|United States|US|',
  'America/North_Dakota/Center|Center|United States|US|',
  'America/Chicago|Chicago|United States|US|Houston,Dallas,Austin,Minneapolis,New Orleans,Nashville,Milwaukee',
  'America/Denver|Denver|United States|US|Salt Lake City,Albuquerque,Boulder',
  'America/Detroit|Detroit|United States|US|',
  'Pacific/Honolulu|Honolulu|United States|US|',
  'America/Indiana/Indianapolis|Indianapolis|United States|US|',
  'America/Juneau|Juneau|United States|US|',
  'America/Indiana/Knox|Knox|United States|US|',
  'America/Los_Angeles|Los Angeles|United States|US|San Francisco,San Jose,Seattle,San Diego,Portland,Silicon Valley,Bay Area',
  'America/Kentucky/Louisville|Louisville|United States|US|',
  'America/Indiana/Marengo|Marengo|United States|US|',
  'America/Menominee|Menominee|United States|US|',
  'America/Metlakatla|Metlakatla|United States|US|',
  'America/Kentucky/Monticello|Monticello|United States|US|',
  'America/North_Dakota/New_Salem|New Salem|United States|US|',
  'America/New_York|New York|United States|US|Boston,Miami,Philadelphia,Atlanta,Washington DC,Charlotte,Pittsburgh',
  'America/Nome|Nome|United States|US|',
  'America/Indiana/Petersburg|Petersburg|United States|US|',
  'America/Phoenix|Phoenix|United States|US|',
  'America/Sitka|Sitka|United States|US|',
  'America/Indiana/Tell_City|Tell City|United States|US|',
  'America/Indiana/Vevay|Vevay|United States|US|',
  'America/Indiana/Vincennes|Vincennes|United States|US|',
  'America/Indiana/Winamac|Winamac|United States|US|',
  'America/Yakutat|Yakutat|United States|US|',
  'America/Montevideo|Montevideo|Uruguay|UY|',
  'Asia/Samarkand|Samarkand|Uzbekistan|UZ|',
  'Asia/Tashkent|Tashkent|Uzbekistan|UZ|',
  'Pacific/Efate|Efate|Vanuatu|VU|',
  'Europe/Rome|Vatican|Vatican City|VA|',
  'America/Caracas|Caracas|Venezuela|VE|',
  'Asia/Bangkok|Ho Chi Minh|Vietnam|VN|',
  'Asia/Ho_Chi_Minh|Ho Chi Minh|Vietnam|VN|Saigon,Hanoi,Da Nang',
  'America/Puerto_Rico|Tortola|Virgin Islands (UK)|VG|',
  'America/Puerto_Rico|St Thomas|Virgin Islands (US)|VI|',
  'Pacific/Tarawa|Wallis|Wallis & Futuna|WF|',
  'Africa/El_Aaiun|El Aaiun|Western Sahara|EH|',
  'Asia/Riyadh|Aden|Yemen|YE|',
  'Africa/Maputo|Lusaka|Zambia|ZM|',
  'Africa/Maputo|Harare|Zimbabwe|ZW|',
  'Europe/Helsinki|Mariehamn|Åland Islands|AX|',
];

/** ISO country code -> flag emoji, via regional indicator symbols. */
export function countryFlag(cc: string): string {
  if (!/^[A-Z]{2}$/.test(cc)) return '\u{1F3F3}';
  return String.fromCodePoint(...[...cc].map(c => 0x1F1E6 + c.charCodeAt(0) - 65));
}

export const TIMEZONES: TzEntry[] = PACKED.map((row) => {
  const [tz, label, country, cc, aliases] = row.split('|');
  return { tz, label, country, cc, aliases: aliases ? aliases.split(',') : [] };
});

/** A search result: the zone, plus the name to show for it. */
export interface TzHit {
  e: TzEntry;
  display: string;  // the alias the user actually typed, when they matched one
  score: number;
}

/** Cities shown first before the user types anything. */
export const POPULAR_TZ = [
  'America/Los_Angeles', 'America/New_York', 'America/Sao_Paulo', 'Europe/London',
  'Europe/Berlin', 'Europe/Paris', 'Africa/Lagos', 'Asia/Dubai', 'Asia/Kolkata',
  'Asia/Singapore', 'Asia/Shanghai', 'Asia/Tokyo', 'Australia/Sydney', 'Pacific/Auckland',
];
